excluded:
- Pods

line_length:
- 200 # warning
- 300 # error

identifier_name:
  min_length: # only min_length
    warning: 1
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

disabled_rules:
- force_try
- trailing_whitespace
